version: "3"
  
services:
  gpt-sangforer:
    network_mode: host
    stdin_open: true
    tty: true
    environment:
       - OPENAI_API_KEY=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
       - HTTP_PROXY='http://localhost:19666'
       - HTTPS_PROXY='http://localhost:19666'
       - NO_PROXY='localhost'  
    image: jdcloudiaas/turta:gpt-engineer
    volumes:
      - ./projects:/project
